Repository team-ppointer/pointer_server, pull requests merged in 2025-02, with the labels that each got.

#32 Feature/#27 문항 검색 api 추가
  .gitignore
  build.gradle
  src/main/generated/com/moplus/moplus_server/domain/concept/domain/QConceptTag.java
  src/main/generated/com/moplus/moplus_server/domain/member/domain/QMember.java
  src/main/generated/com/moplus/moplus_server/domain/problem/domain/QAnswer.java
  src/main/generated/com/moplus/moplus_server/domain/problem/domain/childProblem/QChildProblem.java
  src/main/generated/com/moplus/moplus_server/domain/problem/domain/practiceTest/QPracticeTestTag.java
  src/main/generated/com/moplus/moplus_server/domain/problem/domain/problem/QProblem.java
  src/main/generated/com/moplus/moplus_server/domain/problem/domain/problem/QProblemId.java
  src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ChildProblemMapperImpl.java
  src/main/generated/com/moplus/moplus_server/domain/problem/service/mapper/ProblemMapperImpl.java
  src/main/generated/com/moplus/moplus_server/domain/v0/DetailResultApplication/entity/QDetailResultApplication.java
  src/main/generated/com/moplus/moplus_server/domain/v0/TestResult/entity/QEstimatedRating.java
  src/main/generated/com/moplus/moplus_server/domain/v0/TestResult/entity/QIncorrectProblem.java
  src/main/generated/com/moplus/moplus_server/domain/v0/TestResult/entity/QTestResult.java
  src/main/generated/com/moplus/moplus_server/domain/v0/practiceTest/domain/QPracticeTest.java
  src/main/generated/com/moplus/moplus_server/domain/v0/practiceTest/domain/QProblemForTest.java
  src/main/generated/com/moplus/moplus_server/domain/v0/practiceTest/domain/QProblemImageForTest.java
  src/main/generated/com/moplus/moplus_server/domain/v0/practiceTest/domain/QRatingTable.java
  src/main/generated/com/moplus/moplus_server/global/common/QBaseEntity.java
  src/main/java/com/moplus/moplus_server/domain/problem/controller/ProblemSearchController.java
  src/main/java/com/moplus/moplus_server/domain/problem/domain/practiceTest/PracticeTestTag.java
  src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ConceptTagSearchResponse.java
  src/main/java/com/moplus/moplus_server/domain/problem/dto/response/ProblemSearchGetResponse.java
  src/main/java/com/moplus/moplus_server/domain/problem/repository/ProblemRepository.java
  src/main/java/com/moplus/moplus_server/domain/problem/repository/ProblemSearchRepositoryCustom.java
  src/main/java/com/moplus/moplus_server/global/config/querydsl/QuerydslConfig.java
  src/test/java/com/moplus/moplus_server/domain/problem/repository/ProblemSearchRepositoryCustomTest.java
  src/test/java/com/moplus/moplus_server/domain/problem/service/ProblemSaveServiceTest.java
  src/test/resources/application-h2test.yml
  src/test/resources/concept-tag.sql
  src/test/resources/insert-problem.sql
  src/test/resources/practice-test-tag.sql
Labels: For: API

#30 Feature/#29 문항 세트, 발행 도메인 및 문항세트 생성, 수정, 삭제, 컨펌 API 구현
  src/main/java/com/moplus/moplus_server/domain/problem/domain/problem/Problem.java
  src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetController.java
  src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
  src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSetConfirmStatus.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemReorderRequest.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetPostRequest.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetUpdateRequest.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetRepository.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetDeleteService.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetSaveService.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetUpdateService.java
  src/main/java/com/moplus/moplus_server/domain/publish/domain/Publish.java
  src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
  src/test/java/com/moplus/moplus_server/domain/problemset/ProblemSetServiceTest.java
  src/test/resources/insert-problemset.sql
Labels: Type: Feature

#35 Feature/#33 문항세트 단일 조회, 검색 구현 및 변경사항 반영
  .gitignore
  src/main/java/com/moplus/moplus_server/domain/concept/repository/ConceptTagRepository.java
  src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetController.java
  src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetSearchController.java
  src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
  src/main/java/com/moplus/moplus_server/domain/problemset/domain/Title.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetPostRequest.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/request/ProblemSetUpdateRequest.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetGetResponse.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetSearchGetResponse.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSummaryResponse.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemThumbnailResponse.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetService.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetSaveService.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetUpdateService.java
  src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
  src/test/java/com/moplus/moplus_server/domain/problemset/ProblemSetServiceTest.java
  src/test/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustomTest.java
  src/test/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetServiceTest.java
  src/test/resources/insert-problem-set.sql
  src/test/resources/insert-problem.sql
  src/test/resources/insert-problem2.sql
Labels: Type: Test, Type: Feature

#43 Feature/#42 발행 관련 api 추가
  src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetSearchController.java
  src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetGetResponse.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemSetSearchGetResponse.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetRepository.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetService.java
  src/main/java/com/moplus/moplus_server/domain/publish/controller/PublishController.java
  src/main/java/com/moplus/moplus_server/domain/publish/domain/Publish.java
  src/main/java/com/moplus/moplus_server/domain/publish/dto/request/PublishPostRequest.java
  src/main/java/com/moplus/moplus_server/domain/publish/dto/response/PublishMonthGetResponse.java
  src/main/java/com/moplus/moplus_server/domain/publish/dto/response/PublishProblemSetResponse.java
  src/main/java/com/moplus/moplus_server/domain/publish/repository/PublishRepository.java
  src/main/java/com/moplus/moplus_server/domain/publish/service/PublishDeleteService.java
  src/main/java/com/moplus/moplus_server/domain/publish/service/PublishGetService.java
  src/main/java/com/moplus/moplus_server/domain/publish/service/PublishSaveService.java
  src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
  src/test/java/com/moplus/moplus_server/domain/problemset/ProblemSetServiceTest.java
  src/test/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustomTest.java
  src/test/java/com/moplus/moplus_server/domain/publish/service/PublishServiceTest.java
  src/test/resources/insert-problem-set.sql
  src/test/resources/insert-problem-set2.sql
Labels: Type: Test, Type: Feature

#53 Feature/#47 문항세트 검색 시 문항타이틀, 문항메모 필드 추가
  src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
  src/main/java/com/moplus/moplus_server/domain/problemset/dto/response/ProblemThumbnailResponse.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
  src/main/java/com/moplus/moplus_server/domain/publish/controller/PublishController.java
  src/main/java/com/moplus/moplus_server/domain/publish/dto/request/PublishPostRequest.java
  src/test/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustomTest.java
Labels: Type: Feature

#56 Hotfix/#55 문항세트, 발행 문제 해결
  src/main/java/com/moplus/moplus_server/domain/problemset/controller/ProblemSetSearchController.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
  src/main/java/com/moplus/moplus_server/global/response/ResponseDto.java
  src/main/java/com/moplus/moplus_server/global/response/ResponseDtoAdvice.java
  src/test/java/com/moplus/moplus_server/domain/member/controller/MemberControllerTest.java
  src/test/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustomTest.java
Labels: Type: Feature, Type: Errors/Bugs

#62 [feat/#57] 공통응답 스웨거 스키마 반영
  src/main/java/com/moplus/moplus_server/domain/problem/dto/response/PresignedUrlResponse.java
  src/main/java/com/moplus/moplus_server/global/config/swagger/SwaggerConfig.java
  src/main/java/com/moplus/moplus_server/global/response/ResponseDto.java
  src/main/java/com/moplus/moplus_server/global/response/ResponseDtoAdvice.java
  src/test/java/com/moplus/moplus_server/domain/member/controller/MemberControllerTest.java
Labels: Type: Feature, Type: Docs/Chore

#78 Fix/#77 발행 이슈 해결
  src/main/java/com/moplus/moplus_server/domain/problemset/domain/ProblemSet.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetRepository.java
  src/main/java/com/moplus/moplus_server/domain/problemset/repository/ProblemSetSearchRepositoryCustom.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetGetService.java
  src/main/java/com/moplus/moplus_server/domain/problemset/service/ProblemSetUpdateService.java
  src/main/java/com/moplus/moplus_server/domain/publish/domain/Publish.java
  src/main/java/com/moplus/moplus_server/domain/publish/dto/response/PublishMonthGetResponse.java
  src/main/java/com/moplus/moplus_server/domain/publish/service/PublishSaveService.java
  src/main/java/com/moplus/moplus_server/global/error/ErrorResponse.java
  src/main/java/com/moplus/moplus_server/global/error/GlobalExceptionHandler.java
  src/main/java/com/moplus/moplus_server/global/error/exception/ErrorCode.java
  src/main/java/com/moplus/moplus_server/global/error/exception/ProblemSetToggleException.java
  src/test/java/com/moplus/moplus_server/domain/problemset/ProblemSetServiceTest.java
  src/test/java/com/moplus/moplus_server/domain/publish/service/PublishServiceTest.java
Labels: Type: Feature, Type: Errors/Bugs
